# Advent of Code 2021

This notebook is my solutions to the [Advent of Cocde 2021](https://adventofcode.com/).

In [8]:
import numpy as np
import os


def complete(done=False):
    """
    Print out a message saying whether the task was completed correctly or not.
    Ascii art generated from https://patorjk.com/software/taag.

    Parameters
    ----------
    done: bool
        Set to True to print out the completion text. Default is False.
    """

    comptext = r"""
   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   
"""

    incomptext = r"""
  _______ ____  _____   ____  
 |__   __/ __ \|  __ \ / __ \ 
    | | | |  | | |  | | |  | |
    | | | |  | | |  | | |  | |
    | | | |__| | |__| | |__| |
    |_|  \____/|_____/ \____/ 
"""

    if done:
        print(comptext)
    else:
        print(incomptext)

# directory containing input data
inputdir = "input"

# Day 1

## Part 1

In [6]:
# get the input data
sonar = np.loadtxt(os.path.join(inputdir, "day1.txt"))

In [9]:
increase = np.sum(np.diff(sonar) > 0)

print(f"Number of times slope increases is {increase}")

complete(True)

Number of times slope increases is 1475

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [10]:
window = 3

avesonar = []
rem = len(sonar) % window

for i in range(0, len(sonar) - rem):
    avesonar.append(np.sum(sonar[i:i + window]))

increase = np.sum(np.diff(avesonar) > 0)
print(f"Number of times slope increases is {increase}")

complete(True)

Number of times slope increases is 1516

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



# Day 2

In [11]:
# get the input data
with open(os.path.join(inputdir, "day2.txt"), "r") as fp:
    inputdata = fp.read()

## Part 1

In [14]:
movements = [(line.split()[0], int(line.split()[1])) for line in inputdata.split("\n") if len(line.strip()) > 0]

hpos = 0
dpos = 0

for move in movements:
    if move[0] == "forward":
        hpos += move[1]
    elif move[0] == "up":
        dpos -= move[1]
    else:
        dpos += move[1]

print(f"Depth: {dpos}, horizontal position: {hpos}")
print(f"Multiplied together gives: {dpos * hpos}")

complete(True)

Depth: 1030, horizontal position: 2010
Multiplied together gives: 2070300

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [15]:
aim = 0
hpos = 0
dpos = 0

for move in movements:
    if move[0] == "forward":
        hpos += move[1]
        dpos += (move[1] * aim)
    elif move[0] == "up":
        aim -= move[1]
    else:
        aim += move[1]

print(f"Depth: {dpos}, horizontal position: {hpos}")
print(f"Multiplied together gives: {dpos * hpos}")

complete(True)

Depth: 1034321, horizontal position: 2010
Multiplied together gives: 2078985210

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



# Day 3

In [16]:
# get the input data
with open(os.path.join(inputdir, "day3.txt"), "r") as fp:
    inputdata = fp.read()

## Part 1

In [17]:
binarray = np.array([[int(val) for val in line.strip()] for line in inputdata.split("\n") if len(line.strip()) > 0])

gamma = []
epsilon = []

collen = binarray.shape[0]

for col in binarray.T:
    gamma.append(1 if np.sum(col) > (collen / 2) else 0)
    epsilon.append(int(not gamma[-1]))

decgamma = np.sum([gamma[len(gamma) - (i + 1)] * (2 ** i) for i in range(len(gamma))])
decepsilon = np.sum([epsilon[len(epsilon) - (i + 1)] * (2 ** i) for i in range(len(epsilon))])

print(decgamma)
print(decepsilon)

print(f"Power consumption of the submarine is {decgamma * decepsilon}")

complete(True)

2601
1494
Power consumption of the submarine is 3885894

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [18]:
sublist = np.copy(binarray)
pos = 0
while True:
    col = sublist[:, pos]

    collen = len(col)

    mostcommon = 1 if np.sum(col) >= (collen / 2) else 0
    idx = col == mostcommon

    sublist = sublist[idx, :]

    if np.sum(idx) == 1:
        break

    pos += 1

oxy = sublist[0]

sublist = np.copy(binarray)
pos = 0
while True:
    col = sublist[:, pos]

    collen = len(col)

    leastcommon = 0 if np.sum(col) >= (collen / 2) else 1
    idx = col == leastcommon

    sublist = sublist[idx, :]

    if np.sum(idx) == 1:
        break

    pos += 1

scrub = sublist[0]

decoxy = np.sum([oxy[len(oxy) - (i + 1)] * (2 ** i) for i in range(len(oxy))])
decscrub = np.sum([scrub[len(scrub) - (i + 1)] * (2 ** i) for i in range(len(scrub))])

print(decoxy)
print(decscrub)

print(f"Life support rating: {decoxy * decscrub}")

complete(True)

3775
1159
Life support rating: 4375225

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



# Day 4

In [19]:
# get the input data
with open(os.path.join(inputdir, "day4.txt"), "r") as fp:
    inputdata = fp.read()

## Part 1

In [21]:
lines = inputdata.split("\n")

# get bingo numbers
header = np.array([int(val) for val in lines[0].strip().split(",")])

# get bingo boards
boards = []
grids = []
newboard = []

for i in range(1, len(lines) - 1):
    if len(lines[i].strip()) == 0:
        if len(newboard) != 0:
            boards.append(np.array(newboard))
            grids.append(np.zeros_like(newboard))
            newboard = []
        continue

    newboard.append([int(val) for val in lines[i].strip().split()])

# add on last board
boards.append(np.array(newboard))
grids.append(np.zeros_like(newboard))

# play bingo!
winner = False
bshape = boards[0].shape
for number in header:
    for j in range(len(boards)):
        # find any values equal to number
        hasnum = boards[j] == number
        grids[j][hasnum] = 1

        # check for any winning rows/columns
        if np.any(grids[j].sum(axis=0) == bshape[0]) or np.any(grids[j].sum(axis=1) == bshape[1]):
            winner = True
            break

    if winner:
        break

# get sum of all unmarked numbers on winning grid
usum = boards[j][~grids[j].astype(bool)].sum()

print(f"Final score is {usum * number}")

complete(True)

Final score is 21607

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [22]:
# play bingo (until last board has one)!
winner = False
i = 0
bshape = boards[0].shape
haswon = []

# reset grids
for grid in grids:
    grid[:] = 0

iterator = list(range(len(boards)))

for number in header:
    for j in list(iterator):
        # find any values equal to number
        hasnum = boards[j] == number
        grids[j][hasnum] = 1

        # check for any winning rows/columns
        if np.any(grids[j].sum(axis=0) == bshape[0]) or np.any(grids[j].sum(axis=1) == bshape[1]): 
            haswon.append(iterator.pop(iterator.index(j)))

        if len(iterator) == 0:
            break

    if len(iterator) == 0:
        break

lastwinner = haswon[-1]
usum = boards[lastwinner][~grids[lastwinner].astype(bool)].sum()

print(f"Final score of last winning board is {usum * number}")

complete(True)

Final score of last winning board is 19012

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



# Day 5

In [23]:
# get the input data
with open(os.path.join(inputdir, "day5.txt"), "r") as fp:
    inputdata = fp.read()

## Part 1

In [24]:
linestarts = []
lineends = []
for line in inputdata.split("\n"):
    if len(line.strip()) == 0:
        break
    
    lineend = line.strip().split("->")
    linestarts.append([int(val) for val in lineend[0].strip().split(",")])
    lineends.append([int(val) for val in lineend[1].strip().split(",")])

linestarts = np.array(linestarts, dtype=int)
lineends = np.array(lineends, dtype=int)

xsize = np.max([linestarts[:,0].max(), lineends[:,0].max()]) + 1
ysize = np.max([linestarts[:,1].max(), lineends[:,1].max()]) + 1

ventgrid = np.zeros((xsize, ysize), dtype=int)

for i in range(len(linestarts)):
    # get vertical and horizontal lines
    if linestarts[i, 0] == lineends[i, 0]:
        ycoords = sorted([linestarts[i, 1], lineends[i, 1]])
        ventgrid[linestarts[i, 0], ycoords[0]:ycoords[1] + 1] += 1
    elif linestarts[i, 1] == lineends[i, 1]:
        xcoords = sorted([linestarts[i, 0], lineends[i, 0]])
        ventgrid[xcoords[0]:(xcoords[1] + 1), linestarts[i, 1]] += 1

noverlap = np.sum(ventgrid > 1)

print(f"Number of overlapping lines is {noverlap}")

complete(True)

Number of overlapping lines is 6397

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [25]:
ventgrid = np.zeros((xsize, ysize), dtype=int)

for i in range(len(linestarts)):
    ycoords = sorted([linestarts[i, 1], lineends[i, 1]])
    xcoords = sorted([linestarts[i, 0], lineends[i, 0]])

    # fill in all lines
    if linestarts[i, 0] == lineends[i, 0]:
        ventgrid[linestarts[i, 0], ycoords[0]:ycoords[1] + 1] += 1
    elif linestarts[i, 1] == lineends[i, 1]:
        ventgrid[xcoords[0]:(xcoords[1] + 1), linestarts[i, 1]] += 1
    else:
        stepx = 1 if linestarts[i, 0] <= lineends[i, 0] else -1
        stepy = 1 if linestarts[i, 1] <= lineends[i, 1] else -1

        for j, k in zip(
            range(min([xsize - 1, linestarts[i, 0]]), min([xsize, lineends[i, 0] + stepx]), stepx),
            range(min([ysize - 1, linestarts[i, 1]]), min([ysize, lineends[i, 1] + stepy]), stepy)
        ):
            ventgrid[j, k] += 1

noverlap = np.sum(ventgrid > 1)

print(f"Number of overlapping lines is {noverlap}")

complete(True)

Number of overlapping lines is 22335

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



# Day 6

In [27]:
startfish = np.loadtxt(os.path.join(inputdir, "day6.txt"), delimiter=",")

## Part 1

In [28]:
lanternfish = startfish.tolist()

ndays = 80

# simulate fish for 80 days
for i in range(ndays):
    nfish = len(lanternfish)
    for j in range(nfish):
        if lanternfish[j] == 0:
            lanternfish.append(8)
            lanternfish[j] = 6
        else:
            lanternfish[j] -= 1

    #print(i + 1, len(lanternfish))

nfish = len(lanternfish)

print(f"Number of lantern fish after {ndays} days is {nfish}")

complete(True)


Number of lantern fish after 80 days is 390923

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [29]:
#lanternfish = [1,2,1,1,1,1,1,1,2,1,3,1,1,1,1,3,1,1,1,5,1,1,1,4,5,1,1,1,3,4,1,1,1,1,1,1,1,5,1,4,1,1,1,1,1,1,1,5,1,3,1,3,1,1,1,5,1,1,1,1,1,5,4,1,2,4,4,1,1,1,1,1,5,1,1,1,1,1,5,4,3,1,1,1,1,1,1,1,5,1,3,1,4,1,1,3,1,1,1,1,1,1,2,1,4,1,3,1,1,1,1,1,5,1,1,1,2,1,1,1,1,2,1,1,1,1,4,1,3,1,1,1,1,1,1,1,1,5,1,1,4,1,1,1,1,1,3,1,3,3,1,1,1,2,1,1,1,1,1,1,1,1,1,5,1,1,1,1,5,1,1,1,1,2,1,1,1,4,1,1,1,2,3,1,1,1,1,1,1,1,1,2,1,1,1,2,3,1,2,1,1,5,4,1,1,2,1,1,1,3,1,4,1,1,1,1,3,1,2,5,1,1,1,5,1,1,1,1,1,4,1,1,4,1,1,1,2,2,2,2,4,3,1,1,3,1,1,1,1,1,1,2,2,1,1,4,2,1,4,1,1,1,1,1,5,1,1,4,2,1,1,2,5,4,2,1,1,1,1,4,2,3,5,2,1,5,1,3,1,1,5,1,1,4,5,1,1,1,1,4]
lanternfish = [1]

ndays = 8

setfish = {v: 0 for v in set(lanternfish)}

#for i in setfish:
for i in [1]:
    print(i)
    newfishspawndays = list(range(i, ndays, 8))
    print(newfishspawndays)
    newfish = 0

    for k, j in enumerate(newfishspawndays):
        if k > 0:
            newfish += 2 ** int(np.floor((ndays - j) / 6))

        print(j, newfish)

        #if k > 0:
        #    newfish -= 2 ** (k - 1)
        newfish += 2 ** (k + 1)

    setfish[i] = newfish

nfish = sum([val * lanternfish.count(k) for k, val in setfish.items()])

print(f"Number of lantern fish after {ndays} days is {nfish}")

complete(False)

1
[1]
1 0
Number of lantern fish after 8 days is 2

  _______ ____  _____   ____  
 |__   __/ __ \|  __ \ / __ \ 
    | | | |  | | |  | | |  | |
    | | | |  | | |  | | |  | |
    | | | |__| | |__| | |__| |
    |_|  \____/|_____/ \____/ 



# Day 7

In [32]:
inputdata = np.loadtxt(os.path.join(inputdir, "day7.txt"), delimiter=",").astype(int)

## Part 1

In [34]:
fuel = np.inf

crabpositions = inputdata

for i in range(min(crabpositions), max(crabpositions) + 1):
    posfuel = np.sum(np.abs(crabpositions - i))
    if posfuel < fuel:
        fuel = posfuel

print(f"Spent fuel is {fuel}")

complete(True)

Spent fuel is 353800

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [35]:
fuel = np.inf

crabpositions = inputdata

for i in range(min(crabpositions), max(crabpositions) + 1):
    posfuel = np.sum([sum(range(1, val + 1)) for val in np.abs(crabpositions - i)])
    if posfuel < fuel:
        fuel = posfuel

print(f"Spent fuel is {fuel}")

complete(True)

Spent fuel is 98119739

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



# Day 8

## Part 1

In [37]:
# parse data
input = np.genfromtxt(os.path.join(inputdir, "day8.txt"), dtype=str, delimiter="|")

# get total number of 1s, 4s, 7s, and 8s
ntot = 0
for line in input:
    for val in line[1].strip().split():
        if len(val) in [2, 3, 4, 7]:
            ntot += 1

print(f"The total number of 1s, 4s, 7s and 8s is {ntot}")

complete(True)

The total number of 1s, 4s, 7s and 8s is 278

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [39]:
mappings = {
    0: ["a", "b", "c", "e", "f", "g"],
    1: ["c", "f"],
    2: ["a", "c", "d", "e", "g"],
    3: ["a", "c", "d", "f", "g"],
    4: ["b", "c", "d", "f"],
    5: ["a", "b", "d", "f", "g"],
    6: ["a", "b", "d", "e", "f", "g"],
    7: ["a", "c", "f"],
    8: ["a", "b", "c", "d", "e", "f", "g"],
    9: ["a", "b", "c", "d", "f", "g"]
}

entry = "acedgfb cdfbe gcdfa fbcad dab cefabd cdfgeb eafb cagedb ab"

entries = entry.split()

newmap = {"a": None, "b": None, "c": None, "d": None, "e": None, "f": None, "g": None}

keyentries = [entry for entry in entries if len(entry) in [2, 3, 4, 7]]

overlap = {
    1: {
        4: [letter for letter in mappings[1] if letter in mappings[4]],
        7: [letter for letter in mappings[1] if letter in mappings[7]],
        8: [letter for letter in mappings[1] if letter in mappings[8]]
    },
    4: {
        7: [letter for letter in mappings[4] if letter in mappings[7]],
        8: [letter for letter in mappings[4] if letter in mappings[8]],
    },
    7: {
        8: [letter for letter in mappings[7] if letter in mappings[8]]
    },
}

keyentriessorted = [e[1] for e in sorted(zip([len(entry) for entry in keyentries], keyentries))]

seven_one = [val for val in list(keyentriessorted[1]) if val not in list(keyentriessorted[0])][0]
newmap["a"] = seven_one

four_one = [val for val in list(keyentriessorted[2]) if val not in list(keyentriessorted[0])]


for i, entry in zip([1, 4, 7, 8], keyentriessorted):
    for val, newval in zip(mappings[i], list(entry)):
        if val not in newmap.values():
            newmap[newval] = val

        # break if all positions have been filled
        if all(newmap.values()):
            break
    if all(newmap.values()):
        break

complete(False)


  _______ ____  _____   ____  
 |__   __/ __ \|  __ \ / __ \ 
    | | | |  | | |  | | |  | |
    | | | |  | | |  | | |  | |
    | | | |__| | |__| | |__| |
    |_|  \____/|_____/ \____/ 



# Day 9

In [40]:
with open(os.path.join(inputdir, "day9.txt"), "r") as fp:
    inputdata = fp.read()

input = np.array([[int(val) for val in list(line.strip())] for line in inputdata.split("\n") if len(line.strip()) > 0])

## Part 1

In [41]:
risklevel = 0
lowpoints = []

for i, row in enumerate(input):
    for j, col in enumerate(row):
        comparitors = []

        if j != len(row) - 1:
            comparitors.append(row[j + 1])

        if j != 0:
            comparitors.append(row[j - 1])

        if i != len(input) - 1:
            comparitors.append(input[i + 1, j])

        if i != 0:
            comparitors.append(input[i - 1, j])

        if np.all((col - np.array(comparitors)) < 0.0):
            lowpoints.append((i, j))
            risklevel += (1 + col)

print(f"The risk level is {risklevel}")

complete(True)

The risk level is 575

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [42]:
storedpoints = []

def checkadjacent(startpoint, prevpoint, input):
    storedpoints.append(startpoint)

    i, j = startpoint
    adjacentpoints = []
    adjacentpointvals = []
    if j != input.shape[0] - 1:
         if (i, j + 1) not in storedpoints:
             adjacentpointvals.append(input[i, j + 1])
             adjacentpoints.append((i, j + 1))

    if j != 0:
        if (i, j - 1) not in storedpoints:
            adjacentpointvals.append(input[i, j - 1])
            adjacentpoints.append((i, j - 1))

    if i != input.shape[1] - 1:
        if (i + 1, j) not in storedpoints:
            adjacentpointvals.append(input[i + 1, j])
            adjacentpoints.append((i + 1, j))

    if i != 0:
        if (i - 1, j) not in storedpoints: 
            adjacentpointvals.append(input[i - 1, j])
            adjacentpoints.append((i - 1, j))

    if len(adjacentpoints) == 0:
        return

    for point, pointval in zip(adjacentpoints, adjacentpointvals):
        if pointval != 9 and point != startpoint:
            checkadjacent(point, startpoint, input)

    return

basins = []

for lowpoint in lowpoints:
    storedpoints = []

    checkadjacent(lowpoint, None, input)

    basins.append(set(storedpoints))

sizebasins = sorted(len(basin) for basin in basins)

# get product of biggest three basin sizes
multibasins = 1
for basinsize in sizebasins[-3:]:
    multibasins *= basinsize

print(f"The product of the largest 3 basins is {multibasins}")

complete(True)

The product of the largest 3 basins is 1019700

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



# Day 10

In [43]:
# get the input data
with open(os.path.join(inputdir, "day10.txt"), "r") as fp:
    inputdata = fp.read()

## Part 1

In [44]:
pairs = [("(", ")"), ("[", "]"), ("{", "}"), ("<", ">")]

point = {
    ")": 3,
    "]": 57,
    "}": 1197,
    ">": 25137,
}

syntaxerrorscore = 0

for line in inputdata.split("\n")[:-1]:
    level = 0
    levels = {}
    end = False

    for i, char in enumerate(line.strip()):
        for pair in pairs:
            if char == pair[0]:
                level += 1
                levels[level] = pair[0]
                break
            if char == pair[1]:
                if levels[level] == pair[0]:
                    del levels[level]
                    level -= 1
                    break
                else:
                    end = True
                    break

        if end:
            break

    if end:
        syntaxerrorscore += point[line[i]]

print(f"Syntax error score is {syntaxerrorscore}")

complete(True)

Syntax error score is 321237

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



# Day 11

In [45]:
# get the input data
with open(os.path.join(inputdir, "day11.txt"), "r") as fp:
    inputdata = fp.read()

## Part 1


In [46]:
input = np.array([[int(i) for i in line.strip()] for line in inputdata.split("\n") if len(line.strip()) > 0])

def step(input):
    flashed = []
    nflashed = len(flashed)

    # increase values by 1
    input += 1

    prevflashes = 0

    while True:
        # flashes
        flashes = np.argwhere(input > 9)
         
        for pos in flashes:
            if [pos[0], pos[1]] not in flashed:
                flashed.append([pos[0], pos[1]])

        if prevflashes == flashes.shape[0]:
            break

        # add 1 on to adjacent values
        for pos in flashed:
            for i in range(-1, 2):
                for j in range(-1, 2):
                    x = pos[0] + i
                    y = pos[1] + j

                    if x >= 0 and y >= 0 and x < input.shape[0] and y < input.shape[1]:
                        if not (x == pos[0] and y == pos[1]):
                            input[x, y] += 1

                            if [x, y] not in flashed and input[x, y] > 9:
                                flashed.append([x, y])

        prevflashes = len(flashed)

    # set flashed octopuses to zero
    zeros = input > 9
    input[zeros] = 0
    nflashes = np.sum(zeros)

    return nflashes

nflashes = 0
for i in range(100):
    nflashes += step(input)

print(input)
print(f"Number of flashed after 100 iterations is {nflashes}")

complete(True)

[[4 4 5 7 5 0 0 0 0 0]
 [4 5 7 0 0 0 0 0 0 0]
 [4 6 0 0 0 6 6 0 0 0]
 [4 6 0 0 5 3 3 5 0 0]
 [5 6 6 9 3 2 2 3 5 0]
 [2 6 4 7 2 2 2 2 3 3]
 [2 9 7 9 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 2 2 2 2 2 2 2 2]
 [0 3 2 2 2 2 2 2 2 8]]
Number of flashed after 100 iterations is 1688

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [47]:
input = np.array([[int(i) for i in line.strip()] for line in inputdata.split("\n") if len(line.strip()) > 0])

i = 1
while True:
    _ = step(input)

    if input.sum() == 0:
        break

    i += 1

print(input)
print(f"The number of steps when all octopuses flash is {i}")

complete(True)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
The number of steps when all octopuses flash is 403

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



# Day 12

In [48]:
# get the input data
with open(os.path.join(inputdir, "day12.txt"), "r") as fp:
    inputdata = fp.read()

## Part 1

In [50]:
input = """\
start-A
start-b
A-c
A-b
b-d
A-end
b-end"""

nodes = {}

for line in input.split("\n"):
    a, b = line.strip().split("-")

    if a not in nodes:
        nodes[a] = {"connections": {b: "big" if b.isupper() else "small"}}
    else:
        if b not in nodes[a]["connections"]:
            nodes[a]["connections"][b] = "big" if b.isupper() else "small"

print(nodes)

{'start': {'connections': {'A': 'big', 'b': 'small'}}, 'A': {'connections': {'c': 'small', 'b': 'small', 'end': 'small'}}, 'b': {'connections': {'d': 'small', 'end': 'small'}}}


In [51]:
trips = []

visitedbig = []
visitedsmall = []

positions = ["start"]

branches = {0: {"start": {}}}

level = 1

while True:
    for pos in positions:
        print(pos)
        branches[level] = {pos: {"nodes": list(nodes[pos]["connections"].keys()), "singlevisit": [con for con in nodes[pos]["connections"] if nodes[pos]["connections"][con] == "small"]}}

    positions = list(branches[level].keys())

    level += 1

    if level == 3:
        break


print(branches)

complete(False)

start
start
{0: {'start': {}}, 1: {'start': {'nodes': ['A', 'b'], 'singlevisit': ['b']}}, 2: {'start': {'nodes': ['A', 'b'], 'singlevisit': ['b']}}}

  _______ ____  _____   ____  
 |__   __/ __ \|  __ \ / __ \ 
    | | | |  | | |  | | |  | |
    | | | |  | | |  | | |  | |
    | | | |__| | |__| | |__| |
    |_|  \____/|_____/ \____/ 



# Day 13

In [98]:
with open(os.path.join(inputdir, "day13.txt")) as fp:
    inputdata = fp.readlines()

## Part 1

In [100]:
def print_paper(paper):
    top = "┌" + ("-" * paper.shape[1]) + "┐"
    bottom = "└" + ("-" * paper.shape[1]) + "┘"
    print(top)
    for row in paper:
        print("|" + "".join([(" " if r == 0 else "o") for r in row]) + "|")
    print(bottom)

coords = np.array([[int(x) for x in coord.strip().split(",")] for coord in inputdata if "," in coord])
folds = [[fold.strip().split("=")[0][-1], int(fold.strip().split("=")[1])] for fold in inputdata if "f" in fold]

xmax = coords[:, 0].max()
ymax = coords[:, 1].max()

paper = np.full((ymax + 1, xmax + 1), 0)

for coord in coords:
    paper[coord[1], coord[0]] = 1

# apply first fold only
for fold in folds[:1]:
    if fold[0] == "y":
        top = np.copy(paper[:fold[1], :])
        bottom = np.copy(np.flipud(paper[fold[1] + 1:, :]))
        top[:bottom.shape[0], :] += bottom

        paper = top
    elif fold[0] == "x":
        left = np.copy(paper[:, :fold[1]])
        right = np.copy(np.fliplr(paper[:, fold[1] + 1:]))
        left[:, :right.shape[1]] += right
        
        paper = left
        
    #print_paper(paper)
    #print("\n")
    
ndots = np.sum(paper > 0)
print(f"Number of dots is {ndots}")

complete(True)

Number of dots is 720

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   



## Part 2

In [102]:
paper = np.full((ymax + 1, xmax + 1), 0)

for coord in coords:
    paper[coord[1], coord[0]] = 1

# apply all folds
for fold in folds:
    if fold[0] == "y":
        top = np.copy(paper[:fold[1], :])
        bottom = np.copy(np.flipud(paper[fold[1] + 1:, :]))
        top[:bottom.shape[0], :] += bottom

        paper = top
    elif fold[0] == "x":
        left = np.copy(paper[:, :fold[1]])
        right = np.copy(np.fliplr(paper[:, fold[1] + 1:]))
        left[:, :right.shape[1]] += right
        
        paper = left
        
print_paper(paper)

complete(True)

┌----------------------------------------┐
| oo  o  o ooo  ooo  ooo   oo  o  o oooo |
|o  o o  o o  o o  o o  o o  o o  o    o |
|o  o oooo o  o o  o o  o o  o o  o   o  |
|oooo o  o ooo  ooo  ooo  oooo o  o  o   |
|o  o o  o o    o o  o    o  o o  o o    |
|o  o o  o o    o  o o    o  o  oo  oooo |
└----------------------------------------┘

   _____                      _      _       
  / ____|                    | |    | |      
 | |     ___  _ __ ___  _ __ | | ___| |_ ___ 
 | |    / _ \| '_ ` _ \| '_ \| |/ _ \ __/ _ \
 | |___| (_) | | | | | | |_) | |  __/ ||  __/
  \_____\___/|_| |_| |_| .__/|_|\___|\__\___|
                       | |                   
                       |_|                   

